app: test
service: WebSocket

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-2
  architecture: arm64

plugins:
  - serverless-python-requirements
  - serverless-manifest-plugin

custom:
  manifest:
    output: ./frontend/src/endpoint.json

package:
  individually: true
  patterns:
    - '!**/test'

functions:
  websocketTest:
    module: websocket
    handler: index.handler
    description: Websocket test
    timeout: 60
    memorySize: 128
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
